### ISSUE TITLE
Internal  server error: Icon 'mdi/orbit' not fount

### ISSUE THREAD

**Issue by MarcusYuan** [gureckis/slidev-theme-neversink#14]
Internal  server error: Icon 'mdi/orbit' not fount
![image](https://github.com/user-attachments/assets/e1e2b4f0-8ffb-4d7a-9b30-427a6b3d0702)

**Comment by gureckis** [comment]
are you sure all the dependencies were installed?  pretty that icon is included in this dependency:

`"@iconify-json/mdi": "^1.1.66"`

**Comment by MarcusYuan** [comment]
These dependencies are already installed. I have also tested other themes, and there are no issues with them. I checked this icon on the icon website and found that it does exist

**Comment by gureckis** [comment]
this minimal repo works for me: https://github.com/NYUCCL/talk_template

**Comment by ChristopherWMM** [comment]
I was attempting to monorepo deploy to GitHub pages and was receiving a similar error when I would attempt to use this theme (or any mdi icon) with a globally installed slidev/cli. A workaround that has been successful for me was to just run `build` through npm. I am not sure if @MarcusYuan was using a globally installed cli but that was the cause for me. Here is the error I would get when attempting to build the slides: [https://pastebin.com/cviEY14f](https://pastebin.com/cviEY14f)
