### ISSUE TITLE
Request: Change default image display mode

### ISSUE THREAD

**Issue by NN708** [gureckis/slidev-theme-neversink#18]
I noticed that the default image display mode is set to `inline` in [base.css](https://github.com/gureckis/slidev-theme-neversink/blob/b87c71e501c24485f7fff625b9cd38e466b8687c/styles/base.css#L137), which differs from the approach taken in official Slidev themes. Since most images are typically displayed as individual blocks, could this setting be removed?

**Comment by gureckis** [comment]
sure, make a PR?
